document.addEventListener('DOMContentLoaded',()=>{
 const header=document.getElementById('header'),menu=document.getElementById('menuToggle'),nav=document.getElementById('navLinks'),progress=document.getElementById('scrollProgress'),top=document.getElementById('backToTop');
 menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.innerHTML=open?'<i class="fa-solid fa-xmark"></i>':'<i class="fa-solid fa-bars"></i>';});
 nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.innerHTML='<i class="fa-solid fa-bars"></i>';}));
 const sections=[...document.querySelectorAll('main section[id]')], links=[...document.querySelectorAll('.nav-links a[href^="#"]')];
 function scrollUI(){const y=scrollY;header.classList.toggle('scrolled',y>30);top.classList.toggle('show',y>500);const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h?y/h*100:0)+'%';let current='home';sections.forEach(s=>{if(y>=s.offsetTop-180)current=s.id});links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));}
 addEventListener('scroll',scrollUI,{passive:true});scrollUI();top?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
 const form=document.getElementById('contactForm');
 function valid(id,ok){document.getElementById(id)?.closest('label')?.classList.toggle('invalid',!ok);return ok;}
 form?.addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('name'),email=document.getElementById('email'),wa=document.getElementById('whatsapp'),city=document.getElementById('city'),msg=document.getElementById('message');let ok=true;ok=valid('name',name.value.trim().length>1)&&ok;ok=valid('email',/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim()))&&ok;ok=valid('whatsapp',/^(?:\+94|0)?7\d{8}$/.test(wa.value.replace(/\s/g,'')))&&ok;ok=valid('city',city.value.trim().length>1)&&ok;ok=valid('message',msg.value.trim().length>5)&&ok;if(!ok)return;const btn=form.querySelector('button');btn.disabled=true;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Sending...';try{const r=await fetch(form.action,{method:'POST',headers:{Accept:'application/json'},body:new FormData(form)});if(!r.ok)throw new Error('send');document.getElementById('successBox').style.display='block';form.reset();setTimeout(()=>document.getElementById('successBox').style.display='none',6000)}catch(err){alert('Message could not be sent. Please contact us on WhatsApp.')}finally{btn.disabled=false;btn.innerHTML='<i class="fa-solid fa-paper-plane"></i> Send Inquiry'}});
});
